GroupProject/Controllers/RaceController.cs
using GroupProject.DAL;
using GroupProject.Models;
using GroupProject.ViewModels;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroupProject.Controllers
{
    [RoutePrefix("Races")]
    public class RaceController : Controller
    {

        private GroupProjectContext db = new GroupProjectContext(); 

        // GET: Race
        [Route("Index")]
        public ActionResult Index()
        {

            var races = db.Races
                .Include(r => r.PlanetRaces)
                .ToList();

            var viewModel = new List<RaceViewModel>();

            foreach (var race in races)
            {

                var racePlanets = new List<RacePlanetPartialViewModel>();

                foreach (var planetRace in race.PlanetRaces)
                {
                    racePlanets.Add(new RacePlanetPartialViewModel
                    {
                        ID = planetRace.PlanetID,
                        Name = db.Planets.Find(planetRace.PlanetID).Name
                    });
                }

                viewModel.Add(new RaceViewModel
                {
                    ID = race.RaceID,
                    Classification = race.Classification,
                    AverageHeight = race.AverageHeight,
                    Name = race.Name,
                    Photo = race.Photo,
                    Planets = racePlanets
                }) ;
                
            }

            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupProject/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        <p>Created by "Η καλύτερη ομάδα στον Γκόζμο"</p>
    </div>
</footer>

GroupProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intergalactic Transport Agency</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Partial("_NavBar")

    @RenderBody()

    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

GroupProject/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Races", "Index", "Race")</li>
            </ul>
        </div>
    </div>
</div>